networks:
  gateway-network:
    driver: bridge
    name: gateway-network

services:
  db:
    ports:
      - "8901:5432"
    networks:
      - gateway-network

  app:
    ports:
      - "8080:8000"
    networks:
      - gateway-network

  deltawoot:
    networks:
      - gateway-network

  wa-sidecar-1:
    networks:
      - gateway-network

  session-bridge:
    networks:
      - gateway-network

