[project]
name = "ChannelGateway"
version = "1.0.0"
description = "Channel Gateway for Helpline Platform"
requires-python = "==3.12.*"
dependencies = [
    "asyncpg==0.30.0",
    "fastapi==0.116.1",
    "uvicorn==0.35.0",
    "pydantic-settings==2.10.1",
    "pydantic[email]==2.11.9",
    "aiogram==3.22",
    "tenacity==9.1.2",
    "aiolimiter==1.2.0",
    "structlog==25.4.0",
    "openapi-generator-cli==7.15.0",
    "lazy-imports==1.0.1",
    "python-dateutil==2.9.0.post0",
    "urllib3==2.5.0",
    "aiohttp-retry==2.9.1",
]

[dependency-groups]
dev = [
    "ruff==0.13.0",
    "pytest>=8.4.1",
    "pytest-asyncio>=1.0.0",
    "pytest-mock>=3.14.1",
    "coverage>=7.9.2",
    "pytest-dotenv>=0.5.2",
    "pre-commit>=4.3.0",
    "mypy==1.18.1",
    "httpx==0.28.1"
]

[tool.pytest.ini_options]
pythonpath = ["."]
testpaths = ["tests"]
addopts = "-ras"
env_files = [".test.env"]
log_cli = true
log_cli_format = "%(message)s"
log_cli_level = "DEBUG"