import random

ADJECTIVES = [
    "Amazing",
    "Awesome",
    "Beautiful",
    "Brilliant",
    "Bright",
    "Calm",
    "Charming",
    "Cheerful",
    "Classy",
    "Cool",
    "Courageous",
    "Creative",
    "Delightful",
    "Elegant",
    "Energetic",
    "Fabulous",
    "Fantastic",
    "Friendly",
    "Funny",
    "Generous",
    "Gentle",
    "Glorious",
    "Graceful",
    "Happy",
    "Helpful",
    "Honest",
    "Inspiring",
    "Joyful",
    "Kind",
    "Lovely",
    "Loyal",
    "Magical",
    "Nice",
    "Optimistic",
    "Outstanding",
    "Peaceful",
    "Playful",
    "Polite",
    "Positive",
    "Powerful",
    "Radiant",
    "Reliable",
    "Respectful",
    "Shiny",
    "Smart",
    "Strong",
    "Supportive",
    "Sweet",
    "Talented",
    "Trustworthy",
    "Vibrant",
    "Warm",
    "Wise",
    "Wonderful",
]

NAMES = [
    "Aardvark",
    "Albatross",
    "Alligator",
    "Antelope",
    "Armadillo",
    "Badger",
    "Barracuda",
    "Beaver",
    "Buffalo",
    "Butterfly",
    "Camel",
    "Capybara",
    "Caribou",
    "Caterpillar",
    "Cheetah",
    "Chimpanzee",
    "Cobra",
    "Cougar",
    "Coyote",
    "Crocodile",
    "Dolphin",
    "Dragonfly",
    "Eagle",
    "Falcon",
    "Flamingo",
    "Gazelle",
    "Gecko",
    "Giraffe",
    "Hedgehog",
    "Hippopotamus",
    "Hyena",
    "Iguana",
    "Jaguar",
    "Jellyfish",
    "Kangaroo",
    "Koala",
    "Lemur",
    "Leopard",
    "Llama",
    "Lobster",
    "Meerkat",
    "Mongoose",
    "Octopus",
    "Ostrich",
    "Otter",
    "Panda",
    "Panther",
    "Parrot",
    "Peacock",
    "Penguin",
    "Porcupine",
    "Raccoon",
    "Raven",
    "Salamander",
    "Seahorse",
    "Shark",
    "Sloth",
    "Sparrow",
    "Squirrel",
    "Toucan",
]


def generate_username() -> tuple[str, str]:
    number = random.randint(1, 9999999)
    number_str = f"{number:07d}"
    adjective = random.choice(ADJECTIVES)
    name = random.choice(NAMES)
    return f"{number_str}-{adjective}-{name}", f"rnd_{number_str}"
